version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2345!"
    ports:
      - "5432:5432"
    volumes:
      - /media/vault/docker_data/postgresql_data:/var/lib/postgresql/data 
    networks:
      - local-network

networks: 
  local-network:
    driver: macvlan
